name: send email

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: 
          python -m pip install --upgrade pip
          pip install pipenv 
          
      - id: cache-pipenv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: 
          pipenv install --dev
          
      - name: Set up .env
        run: |
          echo "HOTPOTATO_GMAIL_ACCOUNT=${{ secrets.HOTPOTATO_GMAIL_ACCOUNT }}" >> .env
          echo "HOTPOTATO_GMAIL_APP_PASSWORD=${{ secrets.HOTPOTATO_GMAIL_APP_PASSWORD }}" >> .env
      - name: Send email to test user
        run:
          pipenv run python send.py
