name: send email

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv 
          pipenv install
      - name: Set up .env
        run: |
          echo "HOTPOTATO_GMAIL_ACCOUNT=$HOTPOTATO_GMAIL_ACCOUNT" >> .env
          echo "HOTPOTATO_GMAIL_APP_PASSWORD=$HOTPOTATO_GMAIL_APP_PASSWORD" >> .env
        env:
          HOTPOTATO_GMAIL_ACCOUNT: ${{ secrets.HOTPOTATO_GMAIL_ACCOUNT }}
          HOTPOTATO_GMAIL_APP_PASSWORD: ${{ secrets.HOTPOTATO_GMAIL_APP_PASSWORD }}
      - name: Send email
          pipenv run python send.py
